# -*- coding: utf-8 -*-
"""my_streamlit_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t01fD9z84tnGuxm9mh0dYR08a8eBt_tT
"""

# Import Library
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import dataset
link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df_cars = pd.read_csv(link)

# Création features et sidebar
st.sidebar.title('Regions Cars')
st.sidebar.write("Veuillez sélectionner un ou plusieurs continents.")
selected_continents = st.sidebar.multiselect('Sélectionnez les continents', ['US', 'Europe', 'Japan'])
st.write("Voici les infos par régions sélectionnées :")

# Filtrer le DataFrame en fonction des continents sélectionnés
df_cars_merge = pd.DataFrame()
if "US" in selected_continents :
    df_cars_merge = pd.concat([df_cars_merge, df_cars.loc[df_cars["continent"] == " US."]])
if "Europe" in selected_continents :
    df_cars_merge = pd.concat([df_cars_merge, df_cars.loc[df_cars["continent"] == " Europe."]])
if "Japan" in selected_continents :
    df_cars_merge = pd.concat([df_cars_merge, df_cars.loc[df_cars["continent"] == " Japan."]])
elif df_cars_merge.empty :
    df_cars_merge = df_cars

# Affichez le DataFrame trié
st.write("DataFrame trié :")
df_cars_merge
st.write('\n')

def summarize(df) :

# 1) Calcul statistiques de base grâce à .describe()
    df_final = df.describe(include='all').T

# 2) Affichage des valeurs nulles sur une colonne.
    df_final['NAN'] = df.apply(lambda x: 'OUI' if pd.isna(x).any() else 'NON')

# 3) Calcul % de valeurs nulles : application d'un lambda pour calculer le pourcentage.
    df_final['% NAN'] = df.apply(lambda x : (x.isna().sum() / len(x))*100)

# 4) Affichage des valeurs en doublons sur une colonne.
    df_final['Duplicated'] = df.apply(lambda x: 'OUI' if x.duplicated().any() else 'NON')

# 5) Calcul % de valeurs en doublons : application d'un lambda pour calculer le pourcentage.
    df_final['% Duplicated'] = df.apply(lambda x : (x.duplicated().sum() / len(x))*100)

# 6) Calcul nombre de valeurs uniques : application d'un lambda pour calculer le nombre de valeurs uniques.
    df_final['Uniques'] = df.apply(lambda x : len(x.unique()))

# 7) Création de la heatmap.
    viz_correlation = sns.heatmap(df.select_dtypes(include ='number').corr(), cmap="coolwarm", center=0)
    st.pyplot(viz_correlation.figure)

# 8) Affichage des boxplots de toutes les valeurs numériques.
    # On commence par récupérer les colonnes avec des valeurs numériques (int, float)
    col_num = df.select_dtypes(include=['int', 'float'])

    # On crée une boucle qui crée un graphique global contenant un sous-graphique de type boxplot pour chaque colonne numérique.
    plt.figure(figsize=(8, 10))

    for i, colonne in enumerate(col_num, 1):
        plt.subplot(len(df.columns), 1, i)
        viz_correlation = sns.boxplot(x=df[colonne])
        plt.title(colonne)

    plt.tight_layout()
    plt.show()
    st.pyplot(viz_correlation.figure)

# 9) Affichage des cellules en rouge.
    df_final = df_final.style.apply(lambda column : ['background : red' if value > 0 else '' for value in column], subset=['% NAN', '% Duplicated'])
    df_final
    return df_final

summarize(df_cars_merge)